GET http://localhost:3333/products

####
POST http://localhost:3333/products
Content-Type: application/json

{
  "name": "Keyboard",
  "description": "Mecanic Keyboard",
  "image_url": "https://via.placeholder.com/150",
  "price": 100
}

###
POST http://localhost:3333/auth/login
Content-Type: application/json

{
  "username": "john",
  "password": "john"
}

###
GET http://localhost:3333/orders
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInVzZXJuYW1lIjoiam9obiIsImlhdCI6MTcxNjMwOTA2MiwiZXhwIjoxNzE2MzA5MTIyfQ.B7-LbTUlAtWbUfNaDPjaOgRsmXHl_FKG2G5HDE_f_pU

###
POST http://localhost:3333/orders
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInVzZXJuYW1lIjoiam9obiIsImlhdCI6MTcxNjMxMDIwNCwiZXhwIjoxNzE2MzEwMjY0fQ.cT4TwwP68Wm2N5yfSsKP6Hy3gVmLNSRdoZjkk2B-RK4

{
  "items": [
    {
      "product_id": "7f8c9d8e-9f0a-1b2c-3d4e-5f6g7h8i9j0k",
      "quantity": 1
    },
    {
      "product_id": "668c9d12-9f0a-1b2c-3d4e-5f6g7h8i19d7",
      "quantity": 1
    }
  ],
  "card_hash": "123"
}

# Parei no 1:42:41